title: "Sena Yevenyo"
email: yevesky2020@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the portfolio website for Sena Yevenyo.
baseurl: "/" 
url: "/portfolio-page" 
twitter_username: iamyevesky
github_username:  iamyevesky

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
